language: cpp
notifications:
  email: false
branches:
  only:
    - master


jobs:
  fast_finish: true
  include:
    - name: "xenial gcc-8 | static | find-or-fetch"
      os: linux
      dist: xenial
      compiler: gcc
      env:
        - CXX=g++-8 CC=gcc-8
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
      addons:
        apt:
          update: true
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-8
            - g++-8
            - zlib1g-dev
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/build/Debug/install

    - name: "xenial gcc-8 | shared | find-or-fetch"
      os: linux
      dist: xenial
      compiler: gcc
      env:
        - CXX=g++-8 CC=gcc-8
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DBUILD_SHARED_LIBS:BOOL=ON"
        - CMAKE_GEN="Unix Makefiles"
      addons:
        apt:
          update: true
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-8
            - g++-8
            - zlib1g-dev
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/build/Debug/install

    - name: "xenial gcc-8 | static | apt | find"
      dist: xenial
      os: linux
      compiler: gcc
      env:
        - H5PP_DOWNLOAD_METHOD=find
        - CXX=g++-8 CC=gcc-8
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find   -DH5PP_ENABLE_ASAN:BOOL=ON-DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
      addons:
        apt:
          update: true
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-8
            - g++-8
            - libhdf5-dev
            - libaec-dev
            - libeigen3-dev
            - libspdlog-dev


    - name: "xenial gcc-8 | static | conda-forge | find-or-fetch"
      os: linux
      dist: xenial
      compiler: gcc
      env:
        - H5PP_DOWNLOAD_METHOD=conan
        - CXX=g++-8 CC=gcc-8
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DH5PP_PREFER_CONDA_LIBS:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
        - CONDA_PACKAGES="hdf5 hdf5-static eigen spdlog"
      addons:
        apt:
          update: true
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-8
            - g++-8

    - name: "xenial clang | static | find-or-fetch"
      os: linux
      dist: xenial
      compiler: clang
      env:
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
        - CXX=clang++ CC=clang
      addons:
        apt:
          update: true
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - libstdc++-8-dev
            - zlib1g-dev
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/build/Debug/install

    - name: "bionic gcc | static | find-or-fetch"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/build/Debug/install

    - name: "bionic clang | static | find-or-fetch"
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/build/Debug/install

    - name: "bionic clang | shared | find-or-fetch"
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DH5PP_ENABLE_ASAN:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON"
        - CMAKE_GEN="Unix Makefiles"
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/build/Debug/install

    - name: "bionic gcc | static | conda-forge | find-or-fetch"
      dist: bionic
      os: linux
      compiler: gcc
      env:
        - H5PP_DOWNLOAD_METHOD=find-or-fetch
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DH5PP_ENABLE_ASAN:BOOL=ON -DH5PP_PREFER_CONDA_LIBS:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
        - CONDA_PACKAGES="hdf5 hdf5-static eigen spdlog"


    - name: "bionic gcc | static | apt | find"
      dist: bionic
      os: linux
      compiler: gcc
      env:
        - H5PP_DOWNLOAD_METHOD=find
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find -DH5PP_ENABLE_ASAN:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
      addons:
        apt:
          update: true
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - libhdf5-dev
            - libaec-dev
            - libeigen3-dev
            - libspdlog-dev
            - libfmt-dev

    - name: "bionic clang | static | conan"
      dist: bionic
      os: linux
      compiler: clang
      env:
        - H5PP_DOWNLOAD_METHOD=conan
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=conan -DH5PP_ENABLE_ASAN:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
        - CXX=clang++ CC=clang

    - name: "osx clang | static | conan"
      os: osx
      compiler: clang
      osx_image: xcode11.3
      env:
        - CC=clang
        - CXX=clang++
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=conan -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
        - H5PP_DOWNLOAD_METHOD=conan
      cache:
        directories:
          - $HOME/.conan/data
      addons:
        homebrew:
          packages:
            - conan

    - name: "osx clang | static | find-or-fetch"
      os: osx
      compiler: clang
      osx_image: xcode11.3
      env:
        - CC=clang
        - CXX=clang++
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Unix Makefiles"
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/build/Debug/install

    - name: "osx clang | static | homebrew | find-or-fetch"
      os: osx
      compiler: clang
      osx_image: xcode11.3
      env:
        - CC=clang
        - CXX=clang++
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DBUILD_SHARED_LIBS:BOOL=ON"
        - CMAKE_GEN="Unix Makefiles"
      addons:
        homebrew:
          packages:
            - eigen
            - hdf5
            - spdlog
            - zlib
            - szip


    - name: "windows msvc 2017 | static | conan"
      os: windows
      env:
        - H5PP_DOWNLOAD_METHOD=conan
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=conan -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Visual Studio 15 2017"
        - CMAKE_PLATFORM=x64
      cache:
        directories:
          - $HOME/.conan/data

    - name: "windows msvc 2017 | static | find-or-fetch"
      os: windows
      env:
        - H5PP_DOWNLOAD_METHOD=find-or-fetch
        - CMAKE_FLAGS="-DH5PP_DOWNLOAD_METHOD=find-or-fetch -DBUILD_SHARED_LIBS:BOOL=OFF"
        - CMAKE_GEN="Visual Studio 15 2017"
        - CMAKE_PLATFORM=x64
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/build/Debug/install

# The pre-install script. On windows it will install conan via chocolatey
before_install:
  - echo "Starting before_install"
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco upgrade cmake
      if [[ "$H5PP_DOWNLOAD_METHOD" =~ conan ]]; then
        choco install python3 --version 3.7.4
        export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        python -m pip install --upgrade pip
      fi
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH=/Users/travis/Library/Python/2.7/bin:$PATH
    else
      pip install --user --upgrade pip
    fi
    cmake --version
  - echo "Finished before_install"


install:
  - echo "Starting install"
  - |
    if [[ "$H5PP_DOWNLOAD_METHOD" =~ conan ]]; then
      if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        pip install conan
        export PATH=/c/Program\ Files/Conan/conan:$PATH
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        pip install --user conan --upgrade
      fi
    fi
  - echo "Finished install of pip"


# Setup Build
before_script:
  # On windows PATH's do not get set properly because travis does not restart the shell, so we add them manually
  - echo "Starting before_script"
  - |
    if [[ "$H5PP_DOWNLOAD_METHOD" =~ conan ]]; then
      conan user
      conan profile new default --detect
      conan profile update settings.compiler.libcxx=libstdc++11 default
    fi
    if [[ $CONDA_PACKAGES ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      # Here we just install Miniconda
      pwd
      wget --no-clobber https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      chmod +x miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      source "$HOME/miniconda/etc/profile.d/conda.sh"
      export PATH=$HOME/miniconda/bin:$PATH
      hash -r
      conda config --set always_yes yes --set changeps1 no
      # Useful for debugging any issues with conda
      conda info -a
      # conda update --yes conda
      # conda update -q conda
      conda config --add channels conda-forge
      conda install --yes ${CONDA_PACKAGES}
    fi
  - echo "Finished before_script"
  - cmake --version
# Build and Test
script:
  # Cmake Build
  - echo "Starting script"
  - export MAKEFLAGS=-j1
  - cmake --version
  - cmake -E make_directory build/Debug
  - cd build/Debug
  - |
    cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
          -DH5PP_PRINT_INFO:BOOL=ON \
          -DH5PP_ENABLE_EIGEN3:BOOL=ON \
          -DH5PP_ENABLE_SPDLOG:BOOL=ON \
          -DH5PP_ENABLE_TESTS:BOOL=ON \
          -DH5PP_BUILD_EXAMPLES:BOOL=ON \
          -DCMAKE_BUILD_TYPE=Debug \
           $CMAKE_FLAGS \
          -G "$CMAKE_GEN" \
          -DCMAKE_GENERATOR_PLATFORM=$CMAKE_PLATFORM \
          ../../
  - cmake --build . --parallel 1
  - cmake --build . --target install
  - ctest -C Debug --output-on-failure


after_failure:
  - cat CMakeFiles/CMakeError.log
