name: macOS 11

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  ci:
    name: ${{ matrix.compiler }}-${{ matrix.manager }}
    runs-on: macos-11
    env:
      cache-name: cache-${{ matrix.compiler }}-${{ matrix.manager }}
    strategy:
      fail-fast: false # True stops all on first error. Stick to false when debugging
      matrix:
        include:
          - { compiler: gcc,   manager: cmake }
          - { compiler: gcc,   manager: conan }
          - { compiler: gcc,   manager: find  }
          - { compiler: clang, manager: cmake }
          - { compiler: clang, manager: conan }
          - { compiler: clang, manager: find  }

    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: Setup Python
        uses: actions/setup-python@v4
        if: contains(matrix.manager, 'conan')
        with:
          python-version: '3.x'

      - name: Setup caches
        id: h5pp-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan2
            install/github-actions-${{ matrix.manager }}
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ env.cache-name }}
          max-size: 1000M

      - name: Setup conan
        if: matrix.manager == 'conan'
        run: |
          pip install conan
          conan profile detect --force

      - name: Run CMakePreset
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'github-actions-${{ matrix.manager }}'
          buildPreset: 'github-actions-${{ matrix.manager }}'
          testPreset: 'github-actions-${{ matrix.manager }}'


