name: Ubuntu 18.04

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  ci:
    name: ${{ matrix.compiler }}-${{ matrix.manager }}
    runs-on: ubuntu-18.04
    env:
      cache-name: cache-${{ matrix.compiler }}-${{ matrix.manager }}
    strategy:
      fail-fast: true # True stops all on first error. Stick to false when debugging
      matrix:
        include:
          - { compiler: gcc,   manager: cmake }
          - { compiler: gcc,   manager: conan }
          - { compiler: gcc,   manager: find }
          - { compiler: clang, manager: cmake }
          - { compiler: clang, manager: conan }
          - { compiler: clang, manager: find }

    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: Setup Python
        uses: actions/setup-python@v4
        if: contains(matrix.manager, 'conan')
        with:
          python-version: '3.x'

      - name: Setup caches
        id: h5pp-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan2
            install/github-actions-${{ matrix.manager }}
          key: ${{ runner.os }}-${{ env.cache-name }}

      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}-${{ env.cache-name }}
          max-size: 500M

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ env.cache-name }}
          max-size: 1000M

      - name: Setup gcc
        if: matrix.compiler == 'gcc'
        run: |
          echo "FC=gfortran" >> $GITHUB_ENV
          echo "CC=gcc-7"    >> $GITHUB_ENV
          echo "CXX=g++-7"   >> $GITHUB_ENV

      - name: Setup clang
        if: matrix.compiler == 'clang'
        run: |
          echo "FC=gfortran"     >> $GITHUB_ENV
          echo "CC=clang-9"    >> $GITHUB_ENV
          echo "CXX=clang++-9" >> $GITHUB_ENV

      - name: Setup apt packages
        if: contains(matrix.manager,'find')
        run: sudo apt install ninja-build libhdf5-dev libspdlog-dev libeigen3-dev -y

      - name: Setup conan
        if: matrix.manager == 'conan'
        run: |
          pip install conan
          conan profile detect --force

      - name: Run CMakePreset
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'github-actions-${{ matrix.manager }}'
          buildPreset: 'github-actions-${{ matrix.manager }}'
          testPreset: 'github-actions-${{ matrix.manager }}'



