name: Ubuntu 20.04
# INSPIRATION https://github.com/onqtam/doctest/pull/285/files/875052e18cf5f5f0b9176e59f847b6205f3efb78#

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  ci:
    name: ${{ matrix.compiler }}-conda-[${{ matrix.conda }}]-shared-[${{ matrix.shared }}]-${{ matrix.source }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true # True stops all on first error. Stick to false when debugging
      matrix:
        include:
          - { compiler: gcc,   conda : OFF, shared: OFF, source: fetch }
          - { compiler: gcc,   conda : OFF, shared: ON , source: fetch }
          - { compiler: gcc,   conda : OFF, shared: OFF, source: conan }
          - { compiler: gcc,   conda : OFF, shared: ON , source: conan }
          - { compiler: gcc,   conda : OFF, shared: OFF, source: find-or-fetch }
          - { compiler: gcc,   conda : OFF, shared: ON , source: find-or-fetch }
          - { compiler: gcc,   conda : ON , shared: OFF, source: find-or-fetch }
          - { compiler: gcc,   conda : ON , shared: ON , source: find-or-fetch }
          - { compiler: clang, conda : OFF, shared: OFF, source: fetch }
          - { compiler: clang, conda : OFF, shared: ON , source: fetch }
          - { compiler: clang, conda : OFF, shared: OFF, source: conan }
          - { compiler: clang, conda : OFF, shared: ON , source: conan }
          - { compiler: clang, conda : OFF, shared: OFF, source: find-or-fetch }
          - { compiler: clang, conda : OFF, shared: ON , source: find-or-fetch }
          - { compiler: clang, conda : ON , shared: OFF, source: find-or-fetch }
          - { compiler: clang, conda : ON , shared: ON , source: find-or-fetch }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        if: contains(matrix.source, 'conan')
        with:
          python-version: '3.x'

      - uses: s-weigand/setup-conda@v1
        if: contains(matrix.source,'conda')
        with:
          update-conda: false
          conda-channels: conda-forge

      - name: Setup gcc
        if: matrix.compiler == 'gcc'
        run: |
          sudo apt-get install gcc-10 g++-10 gfortran -y
          echo "::set-env name=FC::gfortran"
          echo "::set-env name=CC::gcc-10"
          echo "::set-env name=CXX::g++-10"

      - name: Setup clang
        if: matrix.compiler == 'clang'
        run: |
          sudo apt-get install clang-10 clang++-10 gfortran -y
          echo "::set-env name=FC::gfortran"
          echo "::set-env name=CC::clang-10"
          echo "::set-env name=CXX::clang++-10"

      - name: Setup apt packages
        if: contains(matrix.source,'find')
        run: sudo apt install libhdf5-dev libspdlog-dev libeigen3-dev -y

      - name: Setup conan
        if: matrix.source == 'conan'
        run: |
          pip install conan
          conan user

      - name: Setup conda
        if: matrix.source == 'conda'
        run: conda install spdlog hdf5 hdf5-static eigen

      - name: Setup cache
        uses: actions/cache@v2
        with:
          env:
            cache-name: ${{ matrix.name }}
          path: |
            ~/.conan/data
            build/Debug/install
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Configure
        shell: bash
        run: |
          cmake -E make_directory build/Debug
          cd build/Debug
          cmake                                                    \
          -DCMAKE_BUILD_TYPE=Debug                                 \
          -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}            \
          -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON                         \
          -DH5PP_ENABLE_EIGEN3:BOOL=ON                             \
          -DH5PP_ENABLE_SPDLOG:BOOL=ON                             \
          -DH5PP_ENABLE_ASAN:BOOL=ON                               \
          -DH5PP_ENABLE_TESTS:BOOL=ON                              \
          -DH5PP_DOWNLOAD_METHOD:STRING=${{ matrix.source }}       \
          -DH5PP_PREFER_CONDA_LIBS:BOOL=${{ matrix.conda }}        \
          -DH5PP_PRINT_INFO:BOOL=ON                                \
          -DH5PP_BUILD_EXAMPLES:BOOL=ON                            \
          -G "Unix Makefiles"                                      \
          ../../

      - name: Build
        run: |
          cd build/Debug
          cmake --build . --parallel 2

      - name: Install
        run: |
          cd build/Debug
          cmake --build . --target install

      - name: Test
        run: |
          cd build/Debug
          ctest -C Debug --output-on-failure



