name: Ubuntu 16.04
# INSPIRATION https://github.com/onqtam/doctest/pull/285/files/875052e18cf5f5f0b9176e59f847b6205f3efb78#

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  ci:
    name: ${{ matrix.compiler }}-conda-[${{ matrix.conda }}]-shared-[${{ matrix.shared }}]-${{ matrix.source }}
    runs-on: ubuntu-16.04
    env:
      cache-name: cache-${{ matrix.compiler }}-conda-[${{ matrix.conda }}]-shared-[${{ matrix.shared }}]-${{ matrix.source }}
    strategy:
      fail-fast: true # True stops all on first error. Stick to false when debugging
      matrix:
        include:
          - { compiler: gcc,   shared: OFF,  conda: OFF, source: cmake }
          - { compiler: gcc,   shared: OFF,  conda: OFF, source: conan }
          - { compiler: gcc,   shared: OFF,  conda: OFF, source: fetch }
          - { compiler: gcc,   shared: OFF,  conda: OFF, source: find  }
          - { compiler: gcc,   shared: OFF,  conda: ON,  source: find  }
          - { compiler: gcc,   shared: ON,   conda: OFF, source: cmake }
          - { compiler: gcc,   shared: ON,   conda: OFF, source: conan }
          - { compiler: gcc,   shared: ON,   conda: OFF, source: fetch }
          - { compiler: gcc,   shared: ON,   conda: OFF, source: find  }
          - { compiler: gcc,   shared: ON,   conda: ON , source: find  }
          - { compiler: clang, shared: OFF,  conda: OFF, source: cmake }
          - { compiler: clang, shared: OFF,  conda: OFF, source: conan }
          - { compiler: clang, shared: OFF,  conda: OFF, source: fetch }
          - { compiler: clang, shared: OFF,  conda: OFF, source: find  }
          - { compiler: clang, shared: OFF,  conda: ON,  source: find  }
          - { compiler: clang, shared: ON,   conda: OFF, source: cmake }
          - { compiler: clang, shared: ON,   conda: OFF, source: conan }
          - { compiler: clang, shared: ON,   conda: OFF, source: fetch }
          - { compiler: clang, shared: ON,   conda: OFF, source: find  }
          - { compiler: clang, shared: ON,   conda: ON , source: find  }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        if: contains(matrix.source, 'conan')
        with:
          python-version: '3.x'

      - uses: s-weigand/setup-conda@v1
        if: contains(matrix.source,'conda')
        with:
          update-conda: false
          conda-channels: conda-forge

      - uses: actions/cache@v2
        with:
          path: |
            ~/.conan/data
#            build/Debug/h5pp-deps-install
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Setup gcc
        if: matrix.compiler == 'gcc'
        run: |
          sudo apt-get install gcc-7 g++-7 gfortran -y
          echo "FC=gfortran" >> $GITHUB_ENV
          echo "CC=gcc-7"    >> $GITHUB_ENV
          echo "CXX=g++-7"   >> $GITHUB_ENV

      - name: Setup clang
        if: matrix.compiler == 'clang'
        run: |
          sudo apt-get install clang-6.0 clang++-6.0 gfortran -y
          echo "FC=gfortran"     >> $GITHUB_ENV
          echo "CC=clang-6.0"    >> $GITHUB_ENV
          echo "CXX=clang++-6.0" >> $GITHUB_ENV

      - name: Setup apt packages
        if: contains(matrix.source,'find')
        run: sudo apt install libhdf5-dev libspdlog-dev libeigen3-dev -y

      - name: Setup conan
        if: matrix.source == 'conan'
        run: |
          pip install conan
          conan user

      - name: Setup conda
        if: matrix.source == 'conda'
        run: conda install spdlog hdf5 hdf5-static eigen

      - name: Configure
        shell: bash
        run: |
          cmake -E make_directory build/Debug
          cd build/Debug
          cmake                                                    \
          -DCMAKE_BUILD_TYPE=Debug                                 \
          -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}            \
          -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON                         \
          -DCMAKE_INSTALL_PREFIX:PATH=~/h5pp                       \
          -DH5PP_ENABLE_EIGEN3:BOOL=ON                             \
          -DH5PP_ENABLE_SPDLOG:BOOL=ON                             \
          -DH5PP_ENABLE_ASAN:BOOL=ON                               \
          -DH5PP_ENABLE_TESTS:BOOL=ON                              \
          -DH5PP_PACKAGE_MANAGER:STRING=${{ matrix.source }}       \
          -DH5PP_PREFER_CONDA_LIBS:BOOL=${{ matrix.conda }}        \
          -DH5PP_PRINT_INFO:BOOL=ON                                \
          -DH5PP_BUILD_EXAMPLES:BOOL=ON                            \
          -G "Unix Makefiles"                                      \
          ../../

      - name: Build
        run: |
          cd build/Debug
          cmake --build . --parallel 2

      - name: Install
        run: |
          cd build/Debug
          cmake --build . --target install

      - name: Test
        run: |
          cd build/Debug
          ctest -C Debug --output-on-failure -R h5pp



